apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-yyrwvypcex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-yyrwvypcex
    app.kubernetes.io/part-of: test-psturc
  name: build-suite-test-component-git-source-yyrwvypcex
  namespace: psturc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: build-suite-test-component-git-source-yyrwvypcex
status:
  loadBalancer: {}
